# Generated by Django 3.0.4 on 2020-04-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bajada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho', models.IntegerField(null=True)),
                ('diametro', models.IntegerField(null=True)),
                ('gramaje', models.IntegerField(null=True)),
                ('peso', models.IntegerField(null=True)),
                ('bobinanro', models.IntegerField(null=True)),
                ('ofnro', models.IntegerField(null=True)),
                ('fecha', models.DateField()),
                ('turno', models.CharField(max_length=1)),
                ('calidad', models.IntegerField(null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
